version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
      - "83:83"
    volumes:
      - ../modules:/var/www
      - ./nginx/:/etc/nginx/conf.d
    links:
      - backend_app
      - auth_app
      - admin_app
      - notifications_app

  backend_app:
    container_name: backend_app
    build: ../modules/backend/_docker
    volumes:
      - ../modules/backend:/var/www/backend
    links:
      - backend_db
    ports:
      - "9000:9000"

  auth_app:
    container_name: auth_app
    build:  ../modules/auth/_docker
    volumes:
      - ../modules/auth:/var/www/auth
    links:
      - auth_db
    ports:
      - "9001:9000"

  admin_app:
    container_name: admin_app
    build:  ../modules/admin/_docker
    volumes:
      - ../modules/admin:/var/www/admin
    links:
      - backend_db
      - auth_db
    ports:
      - "9002:9000"

  notifications_app:
    container_name: notifications_app
    build:  ../modules/notifications/_docker
    volumes:
      - ../modules/notifications:/var/www/notifications
    links:
      - notifications_db
    ports:
      - "9003:9000"

  backend_db:
    image: postgres
    volumes:
      - ../tmp/db/backend:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    ports:
      - "5432:5432"
    container_name: backend_db

  auth_db:
    image: postgres
    volumes:
      - ../tmp/db/auth:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - "5433:5432"
    container_name: auth_db

  notifications_db:
    image: postgres
    volumes:
      - ../tmp/db/notifications:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifications
    ports:
      - "5434:5432"
    container_name: notifications_db

  storage:
    hostname: minio
    image: quay.io/minio/minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./storage/data:/data
    ports:
      - "9005:9000"
      - "9006:9001"

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "password"
    volumes:
      - ./redis:/data
    ports:
      - "8002:6379"